// <auto-generated />
namespace Teeleh.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PhoneNumbeNotRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhoneNumbeNotRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201811181431564_PhoneNumbeNotRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
