// <auto-generated />
namespace Teeleh.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddMorePropertyToPSNAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMorePropertyToPSNAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "201908262131249_AddMorePropertyToPSNAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
